let result;
result = document.all;
result = document.all[6];
result = document.all.length;
result = document.documentElement;
result = document.head;
result = document.body;
result = document.body.children;
result = document.doctype;
result = document.URL;
result = document.characterSet;
result = document.contentType;
result = document.forms;
result = document.forms[0];
result = document.forms[0].method;
result = document.links;
result = document.links[0].id = "all2";
result = document.links[0].innerText = "all2";
result = document.links[0].className;
result = document.links[0].className = "active";
result = document.images;
result = document.images[0];
console.log(result);
