"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Product_1 = require("./Product");
var ProductService_1 = require("./ProductService");
var _productService = new ProductService_1.ProductService();
var result;
result = _productService.getProducts();
var p2 = _productService.getById(2);
var p = new Product_1.Product();
p.id = 2;
p.name = "Iphone";
p.price = 6000;
p.category = "Phone";
_productService.saveProduct(p);
_productService.deleteProduct(p2);
console.log(result);
